### ISSUE TITLE
Download button does not work

### ISSUE THREAD

**Issue by holtgrewe** [urmi-21/ORIS#4]
RE: https://github.com/openjournals/joss-reviews/issues/1589

On windows, instead the following message is displayed "Firefox is already running, but is not responding. The old Firefox process must be closed to open a new window."

**Comment by holtgrewe** [comment]
"Download from NCBI" has the same issue.

**Comment by urmi-21** [comment]
Thanks for reporting this issue. I have not been able to reproduce this error on my Windows (or MAC and Linux) environment. I think the problem may be due to firefox (please see this https://support.mozilla.org/en-US/kb/firefox-already-running-not-responding). 
Please give this another try after killing the firefox process using the Windows Task Manager.

**Comment by holtgrewe** [comment]
Hm, I'm seeing now that if firefox is closed, firefox is opened in an older version (probably the system wide installation vs. the automatically updated one in the user directory). I'm closing this now but maybe there is a more robust way of opening a URL than the one you are using?
